#!/bin/sh

. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
airoha,an7581-evb)
	ucidef_set_led_usbport "usb1" "USB 1" "green:usb-1" "usb1-port1" "usb2-port1"
	ucidef_set_led_usbport "usb2" "USB 2" "green:usb-2" "usb3-port1" "usb4-port1"
	;;
nokia,xg-040g-md)
	LED_PATH="/sys/class/leds/green:internet"
	if [ -d "$LED_PATH" ]; then
		echo "netdev" > "$LED_PATH/trigger" 2>/dev/null
		echo "lan1" > "$LED_PATH/device_name" 2>/dev/null
		echo "1" > "$LED_PATH/link" 2>/dev/null
		echo "1" > "$LED_PATH/tx" 2>/dev/null
		echo "1" > "$LED_PATH/rx" 2>/dev/null
	fi

	ucidef_set_led_usbport "usb1" "USB 3.0" "green:usb-1" "1-1"
	ucidef_set_led_usbport "usb2" "USB 2.0" "green:usb-2" "2-1"
	;;
esac

board_config_flush

exit 0